# Etapa 1: Construção da aplicação
FROM node:14 AS build-stage
WORKDIR /app
COPY pacakge*.json ./
RUN npm install
COPY . .
RUN npm run build

# Etapa 2
# Etapa 2: Servir a aplicação com Nginx
FROM nginx:stable-alpine
COPY --from=build-stage /app/dist /usr/share/nginx/html
COPY nginx-template.conf /etc/nginx/templates/nginx.conf.template
COPY entrypoint.sh /entrypoint.sh

RUN apk add --no-cache gettext

EXPOSE  80

ENTRYPOINT ["/entrypoint.sh"]

CMD ["nginx", "-g", "daemon off;"]