version: '3.1'

services:
  mysql:
    image: mysql:8.0.28
    container_name: mysql_financeiro
    ports:
      - '3306:3306'
    volumes:
      - /opt/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: financeiro
